---
  title: "05-Data_Compare"
  output: html_document
---

# Comparing Data to Priors

To do this section, I really should just use the "get trait data" function 
that is used in pecan because that will show me where/how to deal with the changes
in variable units, both for all the psi variables that are negative but also for 
the variables that are multiplied by 1000. 

```{r}
bety <- betyConnect("/fs/data3/ecowdery/pecan/web/config.php")

pftid <- 1000000132

tropical_species <- tbl(bety, "pfts") %>% dplyr::rename(pft_id = id) %>% filter(pft_id == pftid) %>%
  inner_join(., tbl(bety, "pfts_species"), by = "pft_id") %>% 
  inner_join(., tbl(bety, "species") %>% dplyr::rename(specie_id = id), by = "specie_id") %>% 
  dplyr::select(one_of("pft_id", "name", "specie_id", "genus", "species", "scientificname")) %>% 
  collect()

variables <- c(
  "SLA", 
  "wood_density",
  "leaf_elastic_mod", "wood_elastic_mod",
  "leaf_psi_osmotic", "wood_psi_osmotic",
  "rwc_tlp_wood", 
  "leaf_water_sat", "wood_water_sat",
  "leaf_water_cap", "wood_water_cap",
  "leaf_psi_min", "wood_psi_min",
  "wood_Kmax",
  "wood_psi50",
  "wood_Kexp"
)

variables_ids <- lapply(variables, function(v) tbl(bety, "variables") %>% filter(name == v) %>% pull(id)) %>% unlist()

v_df <- data.frame(variables, variables_ids)

species_ids <- unique(tropical_species$specie_id)

trait_data <- tbl(bety, "traits") %>% filter(specie_id %in% species_ids) %>% 
  filter(variable_id %in% variables_ids) %>% collect()

```

## Wood Density
```{r plot with data wood_density}
v_id <- v_df %>% filter(variables == "wood_density") %>% pull(variables_ids)
wood_density_fit <- tbl(bety, "priors") %>% filter(variable_id == v_id) %>% filter(id == 1000000281) %>% collect()

wood_density_prior <- rdistn(wood_density_fit) 
wood_density_default <- get_ED_default("/fs/data3/ecowdery/ED.Hydro/parameters/pft3_defaults_history.xml", "rho")

p <- prior_plot(prior = wood_density_prior, 
           plot_default = wood_density_default,
           title = sprintf("(wood_density): %s", wood_density_fit$distn),
           type = "prior")

p 

# obs <- trait_data %>% filter(variable_id == v_df$variables_ids[v_df$variables == "wood_density"]) 
# p + geom_density(data = obs, aes(x = mean, fill = "obs"), alpha = .3, color = NA)
```





## SLA 
```{r plot with data SLA}
v_id <- v_df %>% filter(variables == "SLA") %>% pull(variables_ids)
SLA_fit <- tbl(bety, "priors") %>% filter(variable_id == v_id) %>% filter(id == 142) %>% collect()

SLA_prior <- rdistn(SLA_fit) 
SLA_default <- get_ED_default("/fs/data3/ecowdery/ED.Hydro/parameters/pft3_defaults_history.xml", "SLA")

p <- prior_plot(prior = SLA_prior, 
           plot_default = SLA_default,
           title = sprintf("(SLA): %s", SLA_fit$distn),
           type = "prior")

obs <- trait_data %>% filter(variable_id == v_df$variables_ids[v_df$variables == "SLA"]) 
obs$mean <- obs$mean 

p + geom_density(data = obs, aes(x = mean, fill = "obs"), alpha = .3, color = NA)
```





## Kmax

```{r plot with data wood_Kmax}
wood_Kmax_fit <- tbl(bety, "priors") %>% filter(id == wood_Kmax_prior_id) %>% collect()
wood_Kmax_prior <- rdistn(wood_Kmax_fit) # NOTE: Need to convert to m from -m 
wood_Kmax_default <- get_ED_default("/fs/data3/ecowdery/ED.Hydro/parameters/pft3_defaults_history.xml", "wood_Kmax")

p <- prior_plot(prior = wood_Kmax_prior, 
           q = c(0,.995),
           plot_default = wood_Kmax_default,
           title = sprintf("Maximum hydraulic conductivity of the stem (wood_Kmax): %s", wood_Kmax_fit$distn),
           type = "prior")

obs <- trait_data %>% filter(variable_id == v_df$variables_ids[v_df$variables == "wood_Kmax"]) 
obs$mean <- obs$mean 

p + geom_density(data = obs, aes(x = mean, fill = "obs"), alpha = .3, color = NA)
```


## Psi50

```{r plot with data wood_psi50}
wood_psi50_fit <- tbl(bety, "priors") %>% filter(id == wood_psi50_prior_id) %>% collect()
wood_psi50_prior <- -rdistn(wood_psi50_fit) # NOTE: Need to convert to m from -m 

# Calculating default by hand because it is calculated wrong in ED! 
wood_psi50_default <- (-1.09 - (3.57 * default_wood_density ^ 1.73)) * MPa2m
wrong_wood_psi50_default <- get_ED_default(PFT3_defaults_history, "wood_psi50")

p <- prior_plot(prior = wood_psi50_prior, 
           q = c(0.025,1),
           plot_default = wood_psi50_default,
           title = sprintf("Water potential at which 50perc. of stem cond. is lost (wood_psi50): %s", wood_psi50_fit$distn),
           type = "prior") 

obs <- trait_data %>% filter(variable_id == v_df$variables_ids[v_df$variables == "wood_psi50"]) 
obs$mean <- obs$mean 

p + geom_density(data = obs, aes(x = mean, fill = "obs"), alpha = .3, color = NA)

```

## Kexp

```{r plot with data Kexp}
wood_Kexp_fit <- tbl(bety, "priors") %>% filter(id == wood_Kexp_prior_id) %>% collect()
wood_Kexp_prior <- rdistn(wood_Kexp_fit)

# Calculating default by hand because psi50 is calculated wrong in ED!
wood_Kexp_default <- 0.544 * 4. * (-wood_psi50_default / MPa2m) ^ (-0.17)
wrong_wood_Kexp_default <- get_ED_default(PFT3_defaults_history, "wood_Kexp")

p <- prior_plot(prior = wood_Kexp_prior, 
                q = c(0,.5), 
                plot_default = wood_Kexp_default,
                title = sprintf("Water potential at which 50perc. of stem cond. is lost (wood_Kexp): %s", wood_Kexp_fit$distn),
                type = "prior") 

obs <- trait_data %>% filter(variable_id == v_df$variables_ids[v_df$variables == "wood_Kexp"]) 

p + geom_density(data = obs, aes(x = mean, fill = "obs"), alpha = .3, color = NA)

```